import React from 'react';
import appIcon from '../icons/icon.png';

interface AboutPageProps {
  onClose: () => void;
}

const licenseText = `MIT License with Educational Use Clause

Copyright (c) 2026 Dummy Forge Contributors

EDUCATIONAL PURPOSE DISCLAIMER:
This software is designed exclusively for educational, testing, and development purposes. The data generated by this application is entirely fictional and randomly generated.

IMPORTANT DISCLAIMERS:
1. NO REAL DATA: All generated data is synthetic and does not represent real individuals, organizations, or entities.
2. NO LIABILITY: The developers, contributors, and distributors of this software assume NO responsibility or liability for misuse.
3. USER RESPONSIBILITY: Users are responsible for compliance with applicable laws and ethical use.
4. GDPR & PRIVACY COMPLIANCE: Users must ensure compliance with privacy regulations.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.`;

export const AboutPage: React.FC<AboutPageProps> = ({ onClose }) => {
  return (
    <div className="min-h-screen bg-slate-100">
      <header className="border-b bg-white px-8 py-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <img src={appIcon} alt="Dummy Forge" className="h-10 w-10 rounded" />
            <h1 className="text-2xl font-bold">Dummy Forge</h1>
          </div>
          <button
            onClick={onClose}
            className="rounded-md bg-slate-200 px-4 py-2 text-sm font-medium hover:bg-slate-300"
          >
            Back
          </button>
        </div>
      </header>

      <main className="mx-auto max-w-6xl space-y-8 px-8 py-8">
        {/* About Section */}
        <section className="rounded-lg bg-white p-8 shadow">
          <h2 className="mb-4 text-2xl font-bold text-slate-900">About Dummy Forge</h2>
          <p className="mb-4 text-slate-700">
            Dummy Forge is a powerful tool designed to generate realistic dummy data for educational, testing, and development purposes. Whether you're building a database application, testing data pipelines, or learning about data management, Dummy Forge provides customizable, synthetic data that meets your specific needs.
          </p>
          <div className="grid gap-6 md:grid-cols-3">
            <div className="rounded-md bg-blue-50 p-4">
              <h3 className="mb-2 font-semibold text-blue-900">Customizable Fields</h3>
              <p className="text-sm text-blue-800">
                Choose from 30+ predefined field types or create custom fields with specific patterns and configurations.
              </p>
            </div>
            <div className="rounded-md bg-green-50 p-4">
              <h3 className="mb-2 font-semibold text-green-900">Multiple Export Formats</h3>
              <p className="text-sm text-green-800">
                Export your generated data to CSV, SQL, PDF, TXT, and more formats with a single click.
              </p>
            </div>
            <div className="rounded-md bg-purple-50 p-4">
              <h3 className="mb-2 font-semibold text-purple-900">Global Data Support</h3>
              <p className="text-sm text-purple-800">
                Generate realistic data for 195+ countries with localized phone numbers and addresses.
              </p>
            </div>
          </div>
        </section>

        {/* Developer Section */}
        <section className="rounded-lg bg-white p-8 shadow">
          <h2 className="mb-6 text-2xl font-bold text-slate-900">About the Developer</h2>
          <div className="flex flex-col gap-6 md:flex-row">
            <div className="flex-1">
              <h3 className="mb-2 text-xl font-semibold text-slate-900">Kanishka Meddegoda</h3>
              <p className="mb-4 text-slate-700">
                Business Analyst passionate about translating business needs into practical, data-driven solutions. Specializing in requirements analysis, process improvement, and bridging the gap between stakeholders and technology
              </p>
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <svg
                    className="h-5 w-5 text-blue-600"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" />
                  </svg>
                  <a
                    href="https://www.linkedin.com/in/kanishka-me/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:text-blue-800 hover:underline"
                  >
                    kanishka-me
                  </a>
                </div>
                <div className="flex items-center gap-3">
                  <svg
                    className="h-5 w-5 text-blue-400"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path d="M12 2a10 10 0 100 20 10 10 0 000-20zm7.93 9h-3.01a15.4 15.4 0 00-1.3-5.02A8.03 8.03 0 0119.93 11zM12 4.07c.9 1.23 1.58 2.95 1.95 4.93H10.05c.37-1.98 1.05-3.7 1.95-4.93zM6.38 5.98A15.4 15.4 0 005.08 11H2.07a8.03 8.03 0 014.31-5.02zM2.07 13h3.01c.2 1.83.66 3.55 1.3 5.02A8.03 8.03 0 012.07 13zM12 19.93c-.9-1.23-1.58-2.95-1.95-4.93h3.9c-.37 1.98-1.05 3.7-1.95 4.93zm3.62-1.91c.64-1.47 1.1-3.19 1.3-5.02h3.01a8.03 8.03 0 01-4.31 5.02z" />
                  </svg>
                  <a
                    href="https://kanishka.dev"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:text-blue-800 hover:underline"
                  >
                    kanishka.dev
                  </a> 
                </div>
              </div>
            </div>

            <div className="flex flex-col items-center md:items-end">
              <img
                src={appIcon}
                alt="Dummy Forge Icon"
                className="mb-4 h-32 w-32 rounded-lg"
              />
            </div>
          </div>
        </section>

        {/* License Section */}
        <section className="rounded-lg bg-white p-8 shadow">
          <h2 className="mb-4 text-2xl font-bold text-slate-900">License & Terms</h2>
          <div className="rounded-md bg-yellow-50 p-4 mb-4 border border-yellow-200">
            <p className="text-sm font-semibold text-yellow-900">
              ⚠️ IMPORTANT: This tool generates FICTIONAL data for educational purposes only. All data is randomly generated and does not represent real people or entities.
            </p>
          </div>
          <pre className="whitespace-pre-wrap rounded-md bg-slate-50 p-4 text-xs text-slate-700 overflow-auto max-h-96 border border-slate-200">
            {licenseText}
          </pre>
        </section>

        {/* Features Section */}
        <section className="rounded-lg bg-white p-8 shadow">
          <h2 className="mb-4 text-2xl font-bold text-slate-900">Key Features</h2>
          <div className="grid gap-4 md:grid-cols-2">
            <ul className="space-y-2 text-slate-700">
              <li className="flex items-start gap-2">
                <span className="mt-1 inline-block h-2 w-2 rounded-full bg-blue-600"></span>
                <span>30+ predefined field types (names, emails, phone numbers, etc.)</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1 inline-block h-2 w-2 rounded-full bg-blue-600"></span>
                <span>Custom field creation with validation patterns</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1 inline-block h-2 w-2 rounded-full bg-blue-600"></span>
                <span>Demographics configuration (age, gender, location)</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1 inline-block h-2 w-2 rounded-full bg-blue-600"></span>
                <span>Multi-country phone number generation with correct dial codes</span>
              </li>
            </ul>
            <ul className="space-y-2 text-slate-700">
              <li className="flex items-start gap-2">
                <span className="mt-1 inline-block h-2 w-2 rounded-full bg-blue-600"></span>
                <span>Unique field enforcement for emails and IDs</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1 inline-block h-2 w-2 rounded-full bg-blue-600"></span>
                <span>Export to CSV, SQL, PDF, and TXT formats</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1 inline-block h-2 w-2 rounded-full bg-blue-600"></span>
                <span>Real-time data preview with pagination</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1 inline-block h-2 w-2 rounded-full bg-blue-600"></span>
                <span>Generate thousands of records instantly</span>
              </li>
            </ul>
          </div>
        </section>
      </main>

      <footer className="border-t bg-white py-6 text-center text-sm text-slate-600 mt-8">
        <p>© 2026 Dummy Forge. All rights reserved. | Made by <a href="https://kanishka.dev" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 hover:underline">Kanishka Meddegoda</a></p>
      </footer>
    </div>
  );
};
