import React from 'react';

interface LicenseAgreementProps {
  open: boolean;
  onAccept: () => void;
  onDecline: () => void;
}

const licenseText = `MIT License with Educational Use Clause

Copyright (c) 2026 Dummy Forge Contributors

EDUCATIONAL PURPOSE DISCLAIMER:
This software is designed exclusively for educational, testing, and development purposes. The data generated by this application is entirely fictional and randomly generated.

IMPORTANT DISCLAIMERS:
1. NO REAL DATA: All generated data is synthetic and does not represent real individuals, organizations, or entities.
2. NO LIABILITY: The developers, contributors, and distributors of this software assume NO responsibility or liability for misuse.
3. USER RESPONSIBILITY: Users are responsible for compliance with applicable laws and ethical use.
4. GDPR & PRIVACY COMPLIANCE: Users must ensure compliance with privacy regulations.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction.`;

export const LicenseAgreement: React.FC<LicenseAgreementProps> = ({ open, onAccept, onDecline }) => {
  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="w-full max-w-2xl rounded-lg bg-white shadow-xl">
        <div className="border-b px-6 py-4">
          <h2 className="text-xl font-semibold">Educational Use Agreement</h2>
        </div>
        <div className="max-h-96 space-y-3 overflow-y-auto px-6 py-4 text-sm">
          <p className="font-semibold text-red-600">
            IMPORTANT: This tool generates FICTIONAL data for educational purposes only.
          </p>
          <ul className="list-disc space-y-1 pl-5 text-slate-700">
            <li>All data is randomly generated and does not represent real people</li>
            <li>You are responsible for using this data ethically and legally</li>
            <li>The developers assume NO liability for misuse</li>
            <li>Do not use for fraud, identity theft, or illegal purposes</li>
          </ul>
          <pre className="whitespace-pre-wrap rounded-md bg-slate-50 p-3 text-xs text-slate-600">
            {licenseText}
          </pre>
        </div>
        <div className="flex justify-end gap-3 border-t px-6 py-4">
          <button
            className="rounded-md border border-slate-300 px-4 py-2 text-sm"
            onClick={onDecline}
          >
            Decline
          </button>
          <button
            className="rounded-md bg-blue-600 px-4 py-2 text-sm text-white"
            onClick={onAccept}
          >
            I Accept
          </button>
        </div>
      </div>
    </div>
  );
};
