export interface PhoneRule {
  dialCode: string;
  minLength: number;
  maxLength: number;
}

export const phoneRules: Record<string, PhoneRule> = {
  // Asia
  AF: { dialCode: '93', minLength: 9, maxLength: 9 },
  BD: { dialCode: '880', minLength: 10, maxLength: 10 },
  BT: { dialCode: '975', minLength: 8, maxLength: 8 },
  BN: { dialCode: '673', minLength: 7, maxLength: 7 },
  KH: { dialCode: '855', minLength: 8, maxLength: 9 },
  CN: { dialCode: '86', minLength: 11, maxLength: 11 },
  IN: { dialCode: '91', minLength: 10, maxLength: 10 },
  ID: { dialCode: '62', minLength: 9, maxLength: 11 },
  JP: { dialCode: '81', minLength: 10, maxLength: 10 },
  KZ: { dialCode: '7', minLength: 10, maxLength: 10 },
  KG: { dialCode: '996', minLength: 9, maxLength: 9 },
  LA: { dialCode: '856', minLength: 9, maxLength: 10 },
  MY: { dialCode: '60', minLength: 9, maxLength: 10 },
  MV: { dialCode: '960', minLength: 7, maxLength: 7 },
  MN: { dialCode: '976', minLength: 8, maxLength: 8 },
  MM: { dialCode: '95', minLength: 8, maxLength: 10 },
  NP: { dialCode: '977', minLength: 10, maxLength: 10 },
  KP: { dialCode: '850', minLength: 10, maxLength: 10 },
  PK: { dialCode: '92', minLength: 10, maxLength: 10 },
  PH: { dialCode: '63', minLength: 10, maxLength: 10 },
  SG: { dialCode: '65', minLength: 8, maxLength: 8 },
  KR: { dialCode: '82', minLength: 9, maxLength: 10 },
  LK: { dialCode: '94', minLength: 9, maxLength: 9 },
  TW: { dialCode: '886', minLength: 9, maxLength: 9 },
  TJ: { dialCode: '992', minLength: 9, maxLength: 9 },
  TH: { dialCode: '66', minLength: 9, maxLength: 9 },
  TM: { dialCode: '993', minLength: 8, maxLength: 8 },
  UZ: { dialCode: '998', minLength: 9, maxLength: 9 },
  VN: { dialCode: '84', minLength: 9, maxLength: 10 },

  // Middle East
  BH: { dialCode: '973', minLength: 8, maxLength: 8 },
  IR: { dialCode: '98', minLength: 10, maxLength: 10 },
  IQ: { dialCode: '964', minLength: 10, maxLength: 10 },
  IL: { dialCode: '972', minLength: 9, maxLength: 9 },
  JO: { dialCode: '962', minLength: 9, maxLength: 9 },
  KW: { dialCode: '965', minLength: 8, maxLength: 8 },
  LB: { dialCode: '961', minLength: 8, maxLength: 8 },
  OM: { dialCode: '968', minLength: 8, maxLength: 8 },
  PS: { dialCode: '970', minLength: 9, maxLength: 9 },
  QA: { dialCode: '974', minLength: 8, maxLength: 8 },
  SA: { dialCode: '966', minLength: 9, maxLength: 9 },
  SY: { dialCode: '963', minLength: 9, maxLength: 9 },
  TR: { dialCode: '90', minLength: 10, maxLength: 10 },
  AE: { dialCode: '971', minLength: 9, maxLength: 9 },
  YE: { dialCode: '967', minLength: 9, maxLength: 9 },

  // Europe
  AL: { dialCode: '355', minLength: 9, maxLength: 9 },
  AD: { dialCode: '376', minLength: 6, maxLength: 6 },
  AM: { dialCode: '374', minLength: 8, maxLength: 8 },
  AT: { dialCode: '43', minLength: 10, maxLength: 11 },
  AZ: { dialCode: '994', minLength: 9, maxLength: 9 },
  BY: { dialCode: '375', minLength: 9, maxLength: 9 },
  BE: { dialCode: '32', minLength: 9, maxLength: 9 },
  BA: { dialCode: '387', minLength: 8, maxLength: 8 },
  BG: { dialCode: '359', minLength: 9, maxLength: 9 },
  HR: { dialCode: '385', minLength: 9, maxLength: 9 },
  CY: { dialCode: '357', minLength: 8, maxLength: 8 },
  CZ: { dialCode: '420', minLength: 9, maxLength: 9 },
  DK: { dialCode: '45', minLength: 8, maxLength: 8 },
  EE: { dialCode: '372', minLength: 7, maxLength: 8 },
  FI: { dialCode: '358', minLength: 9, maxLength: 10 },
  FR: { dialCode: '33', minLength: 9, maxLength: 9 },
  GE: { dialCode: '995', minLength: 9, maxLength: 9 },
  DE: { dialCode: '49', minLength: 10, maxLength: 11 },
  GR: { dialCode: '30', minLength: 10, maxLength: 10 },
  HU: { dialCode: '36', minLength: 9, maxLength: 9 },
  IS: { dialCode: '354', minLength: 7, maxLength: 7 },
  IE: { dialCode: '353', minLength: 9, maxLength: 9 },
  IT: { dialCode: '39', minLength: 9, maxLength: 10 },
  LV: { dialCode: '371', minLength: 8, maxLength: 8 },
  LI: { dialCode: '423', minLength: 7, maxLength: 7 },
  LT: { dialCode: '370', minLength: 8, maxLength: 8 },
  LU: { dialCode: '352', minLength: 9, maxLength: 9 },
  MT: { dialCode: '356', minLength: 8, maxLength: 8 },
  MD: { dialCode: '373', minLength: 8, maxLength: 8 },
  MC: { dialCode: '377', minLength: 8, maxLength: 8 },
  ME: { dialCode: '382', minLength: 8, maxLength: 8 },
  NL: { dialCode: '31', minLength: 9, maxLength: 9 },
  MK: { dialCode: '389', minLength: 8, maxLength: 8 },
  NO: { dialCode: '47', minLength: 8, maxLength: 8 },
  PL: { dialCode: '48', minLength: 9, maxLength: 9 },
  PT: { dialCode: '351', minLength: 9, maxLength: 9 },
  RO: { dialCode: '40', minLength: 10, maxLength: 10 },
  RU: { dialCode: '7', minLength: 10, maxLength: 10 },
  SM: { dialCode: '378', minLength: 10, maxLength: 10 },
  RS: { dialCode: '381', minLength: 9, maxLength: 9 },
  SK: { dialCode: '421', minLength: 9, maxLength: 9 },
  SI: { dialCode: '386', minLength: 8, maxLength: 8 },
  ES: { dialCode: '34', minLength: 9, maxLength: 9 },
  SE: { dialCode: '46', minLength: 9, maxLength: 9 },
  CH: { dialCode: '41', minLength: 9, maxLength: 9 },
  UA: { dialCode: '380', minLength: 9, maxLength: 9 },
  GB: { dialCode: '44', minLength: 10, maxLength: 10 },
  VA: { dialCode: '379', minLength: 10, maxLength: 10 },

  // Africa
  DZ: { dialCode: '213', minLength: 9, maxLength: 9 },
  AO: { dialCode: '244', minLength: 9, maxLength: 9 },
  BJ: { dialCode: '229', minLength: 8, maxLength: 8 },
  BW: { dialCode: '267', minLength: 8, maxLength: 8 },
  BF: { dialCode: '226', minLength: 8, maxLength: 8 },
  BI: { dialCode: '257', minLength: 8, maxLength: 8 },
  CM: { dialCode: '237', minLength: 9, maxLength: 9 },
  CV: { dialCode: '238', minLength: 7, maxLength: 7 },
  CF: { dialCode: '236', minLength: 8, maxLength: 8 },
  TD: { dialCode: '235', minLength: 8, maxLength: 8 },
  KM: { dialCode: '269', minLength: 7, maxLength: 7 },
  CG: { dialCode: '242', minLength: 9, maxLength: 9 },
  CD: { dialCode: '243', minLength: 9, maxLength: 9 },
  DJ: { dialCode: '253', minLength: 8, maxLength: 8 },
  EG: { dialCode: '20', minLength: 10, maxLength: 10 },
  GQ: { dialCode: '240', minLength: 9, maxLength: 9 },
  ER: { dialCode: '291', minLength: 7, maxLength: 7 },
  SZ: { dialCode: '268', minLength: 8, maxLength: 8 },
  ET: { dialCode: '251', minLength: 9, maxLength: 9 },
  GA: { dialCode: '241', minLength: 7, maxLength: 8 },
  GM: { dialCode: '220', minLength: 7, maxLength: 7 },
  GH: { dialCode: '233', minLength: 9, maxLength: 9 },
  GN: { dialCode: '224', minLength: 9, maxLength: 9 },
  GW: { dialCode: '245', minLength: 7, maxLength: 7 },
  CI: { dialCode: '225', minLength: 10, maxLength: 10 },
  KE: { dialCode: '254', minLength: 10, maxLength: 10 },
  LS: { dialCode: '266', minLength: 8, maxLength: 8 },
  LR: { dialCode: '231', minLength: 8, maxLength: 8 },
  LY: { dialCode: '218', minLength: 10, maxLength: 10 },
  MG: { dialCode: '261', minLength: 9, maxLength: 9 },
  MW: { dialCode: '265', minLength: 9, maxLength: 9 },
  ML: { dialCode: '223', minLength: 8, maxLength: 8 },
  MR: { dialCode: '222', minLength: 8, maxLength: 8 },
  MU: { dialCode: '230', minLength: 8, maxLength: 8 },
  MA: { dialCode: '212', minLength: 9, maxLength: 9 },
  MZ: { dialCode: '258', minLength: 9, maxLength: 9 },
  NA: { dialCode: '264', minLength: 9, maxLength: 9 },
  NE: { dialCode: '227', minLength: 8, maxLength: 8 },
  NG: { dialCode: '234', minLength: 10, maxLength: 10 },
  RW: { dialCode: '250', minLength: 9, maxLength: 9 },
  ST: { dialCode: '239', minLength: 7, maxLength: 7 },
  SN: { dialCode: '221', minLength: 9, maxLength: 9 },
  SC: { dialCode: '248', minLength: 7, maxLength: 7 },
  SL: { dialCode: '232', minLength: 8, maxLength: 8 },
  SO: { dialCode: '252', minLength: 8, maxLength: 8 },
  ZA: { dialCode: '27', minLength: 9, maxLength: 9 },
  SS: { dialCode: '211', minLength: 9, maxLength: 9 },
  SD: { dialCode: '249', minLength: 9, maxLength: 9 },
  TZ: { dialCode: '255', minLength: 9, maxLength: 9 },
  TG: { dialCode: '228', minLength: 8, maxLength: 8 },
  TN: { dialCode: '216', minLength: 8, maxLength: 8 },
  UG: { dialCode: '256', minLength: 9, maxLength: 9 },
  ZM: { dialCode: '260', minLength: 9, maxLength: 9 },
  ZW: { dialCode: '263', minLength: 9, maxLength: 9 },

  // North America
  CA: { dialCode: '1', minLength: 10, maxLength: 10 },
  US: { dialCode: '1', minLength: 10, maxLength: 10 },
  MX: { dialCode: '52', minLength: 10, maxLength: 10 },

  // Central America & Caribbean
  AG: { dialCode: '1', minLength: 10, maxLength: 10 },
  BS: { dialCode: '1', minLength: 10, maxLength: 10 },
  BB: { dialCode: '1', minLength: 10, maxLength: 10 },
  BZ: { dialCode: '501', minLength: 7, maxLength: 7 },
  CR: { dialCode: '506', minLength: 8, maxLength: 8 },
  CU: { dialCode: '53', minLength: 8, maxLength: 8 },
  DM: { dialCode: '1', minLength: 10, maxLength: 10 },
  DO: { dialCode: '1', minLength: 10, maxLength: 10 },
  SV: { dialCode: '503', minLength: 8, maxLength: 8 },
  GD: { dialCode: '1', minLength: 10, maxLength: 10 },
  GT: { dialCode: '502', minLength: 8, maxLength: 8 },
  HT: { dialCode: '509', minLength: 8, maxLength: 8 },
  HN: { dialCode: '504', minLength: 8, maxLength: 8 },
  JM: { dialCode: '1', minLength: 10, maxLength: 10 },
  NI: { dialCode: '505', minLength: 8, maxLength: 8 },
  PA: { dialCode: '507', minLength: 8, maxLength: 8 },
  KN: { dialCode: '1', minLength: 10, maxLength: 10 },
  LC: { dialCode: '1', minLength: 10, maxLength: 10 },
  VC: { dialCode: '1', minLength: 10, maxLength: 10 },
  TT: { dialCode: '1', minLength: 10, maxLength: 10 },

  // South America
  AR: { dialCode: '54', minLength: 10, maxLength: 10 },
  BO: { dialCode: '591', minLength: 8, maxLength: 8 },
  BR: { dialCode: '55', minLength: 11, maxLength: 11 },
  CL: { dialCode: '56', minLength: 9, maxLength: 9 },
  CO: { dialCode: '57', minLength: 10, maxLength: 10 },
  EC: { dialCode: '593', minLength: 9, maxLength: 9 },
  GY: { dialCode: '592', minLength: 7, maxLength: 7 },
  PY: { dialCode: '595', minLength: 9, maxLength: 9 },
  PE: { dialCode: '51', minLength: 9, maxLength: 9 },
  SR: { dialCode: '597', minLength: 7, maxLength: 7 },
  UY: { dialCode: '598', minLength: 8, maxLength: 8 },
  VE: { dialCode: '58', minLength: 10, maxLength: 10 },

  // Oceania
  AU: { dialCode: '61', minLength: 9, maxLength: 9 },
  FJ: { dialCode: '679', minLength: 7, maxLength: 7 },
  KI: { dialCode: '686', minLength: 5, maxLength: 5 },
  MH: { dialCode: '692', minLength: 7, maxLength: 7 },
  FM: { dialCode: '691', minLength: 7, maxLength: 7 },
  NR: { dialCode: '674', minLength: 7, maxLength: 7 },
  NZ: { dialCode: '64', minLength: 9, maxLength: 10 },
  PW: { dialCode: '680', minLength: 7, maxLength: 7 },
  PG: { dialCode: '675', minLength: 8, maxLength: 8 },
  WS: { dialCode: '685', minLength: 7, maxLength: 7 },
  SB: { dialCode: '677', minLength: 7, maxLength: 7 },
  TO: { dialCode: '676', minLength: 5, maxLength: 7 },
  TV: { dialCode: '688', minLength: 5, maxLength: 6 },
  VU: { dialCode: '678', minLength: 7, maxLength: 7 }
};
